-- Product Table
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm5317269', 'Adsapommanor', 159, 'Reptile', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm2336005', 'Rapdimplanor', 185, 'Dog', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm3096895', 'Aderupavil', 124, 'Dog', 'antibiotic');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm4795236', 'Lomsapplavil', 197, 'Reptile', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm3266758', 'Cipsapplanor', 178, 'Bird', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm5032142', 'Klizapicalax', 198, 'Cat', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm6047660', 'Dopdudanor', 84, 'Bird', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm3412836', 'Upsipackalax', 61, 'Bird', 'antibiotic');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm1465537', 'Monhuponalax', 161, 'Bird', 'flea and tick medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm1043663', 'Groquestanor', 192, 'Reptile', 'flea medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm7227887', 'Bardudollanor', 54, 'Cat', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm3387519', 'Dopzapplalax', 153, 'Bird', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm2423522', 'Varkilaquanor', 177, 'Reptile', 'flea medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm7745135', 'Frokilplalax', 58, 'Bird', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm1723362', 'Emericalax', 111, 'Reptile', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm8800660', 'Surfropilalax', 102, 'Cat', 'antibiotic');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm8639347', 'Adsapaquavil', 199, 'Reptile', 'flea and tick medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm4826505', 'Zeerobicavil', 134, 'Dog', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm7702065', 'Hapkilicanor', 121, 'Dog', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm3244116', 'Haphupupalax', 57, 'Dog', 'antibiotic');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm6877298', 'Rapjubupavil', 137, 'Dog', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm0052363', 'Uncadepavil', 177, 'Reptile', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm7698388', 'Barkilefalax', 84, 'Dog', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm5412208', 'Varrobanor', 72, 'Reptile', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'm5834759', 'Klibanavil', 194, 'Bird', 'heart medication');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f5317269', 'Blue Hen Premium', 159, 'Cat', 'Kibble');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f2336005', 'Blue Buffalo', 85, 'Cat', 'Kibble');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f3096895', 'Blue Hen', 124, 'Cat', 'Kibble');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f4795236', 'Insect Mix', 27, 'Reptile', 'Wet food');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f3266758', 'Blue Hen', 178, 'Cat', 'Wet food');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f5032142', 'Blue Hen', 38, 'Dog', 'Wet food');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f6047660', 'Red Buffalo', 84, 'Dog', 'Kibble');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f3412836', 'Blue Buffalo', 58, 'Cat', 'Kibble');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f1465537', 'Blue Hen', 61, 'Cat', 'Kibble');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'f1043663', 'Blue Hen Premium', 92, 'Dog', 'Kibble');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g5317269', 'Lee''s Clarifying Shampoo', 59, 'Dog', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g2336005', 'Lee''s Clarifying Shampoo', 85, 'Dog', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g3096895', 'Essence Clarifying Shampoo', 24, 'Dog', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g4795236', 'Janna''s Detangling Shampoo', 97, 'Dog', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g3266758', 'Lee''s Detox Shampoo', 78, 'Dog', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g5032142', 'Lee''s Clarifying Shampoo', 98, 'Cat', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g6047660', 'Lee''s Clarifying Shampoo', 84, 'Cat', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g3412836', 'Janna''s Clarifying Shampoo', 61, 'Cat', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g1465537', 'Burt''s Detox Shampoo', 61, 'Dog', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 'g1043663', 'Revival Clarifying Shampoo', 92, 'Cat', 'Pet Grooming');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 't5317269', 'Baricator', 29, 'Dog', 'Ball');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 't2336005', 'Kliin', 36, 'Cat', 'Scratch Pad');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 't3096895', 'Adan', 29, 'Cat', 'Scratch Pad');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 't4795236', 'Dopex', 29, 'Dog', 'Bone');
INSERT INTO group_7.products( id, product_name, product_price, product_category, product_description ) VALUES ( 't3266758', 'Emistor', 44, 'Dog', 'Ball');

--